--CRAIACAO DE TABELA SEM CONTRAINT

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(10),
        NOME VARCHAR2(200),
        SEXO CHAR(1),
        DATA_NASC DATE
        );
        
--EXCLUSAO DE TABELA ALUNO

DROP TABLE ALUNO CASCADE CONSTRAINTS;

--CRIACAO DE TABELA COM CONSTRAINT NOT NULL

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(10) NOT NULL,
        NOME VARCHAR2(200) NOT NULL,
        SEXO CHAR(1),
        DATA_NASC DATE
        );

--CRIACAO DE TABELA COM CONSTRAINT NOT NULL NOMEADA

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(10) CONSTRAINT NN_ALUNO_MATRICULA NOT NULL,
        NOME VARCHAR2(200) CONSTRAINT NN_ALUNO_NOME NOT NULL,
        SEXO CHAR(1),
        DATA_NASC DATE
        );
        
--CRIACAO DA TABELA MATERIA COM CONTRAINT UNIQUE

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4) NOT NULL,
        DESCRICAO VARCHAR2(200) UNIQUE
        );
        
--EXCLUSAO DE TABELA MATERIA

DROP TABLE MATERIA CASCADE CONSTRAINTS;   

--CRIACAO DE TABELA MATERIA COM CONTRAINT NOMEADA - NIVEL COLUNA

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4) CONSTRAINT NN_MATERIA_CODIGO NOT NULL,
        DESCRICAO VARCHAR(200) CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE
        );
        
-- CRIACAO DE TABELA MATERIA COM CONTRAINT NOMEADA - NIVEL TABELA

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4) CONSTRAINT NN_MATERIA_CODIGO NOT NULL,
        DESCRICAO VARCHAR2(200),
        CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE(DESCRICAO)
        );
        
--CRIACAO DA TABELA MATERIA COM CONSTRAINT PRIMARY KEY

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4) PRIMARY KEY,
        DESCRICAO VARCHAR2(200) UNIQUE
        );
        
--CRIACAO DA TABELA MATERIA COM CONSTRAINT NOMEADA - NIVEL COLUNA

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4) CONSTRAINT PK_MATERIA_CODIGO PRIMARY KEY,
        DESCRICAO VARCHAR2(200) CONSTRAINT UK_MATERIA_DESCRICAO UNIQUE
        );
        
--CRIACAO DA TABELA MATERIA COM CONSTRAINT NOMEADA - NIVEL TABELA

CREATE TABLE
    MATERIA (
        CODIGO NUMBER(4),
        SIGLA CHAR(2),
        DESCRICAO VARCHAR2(200) UNIQUE,
        CONSTRAINT PK_MATERIA_CODIGO_SIGLA PRIMARY KEY(CODIGO,SIGLA)
        );
        
--CRIACAO DA TABELA ALUNO COM CONSTRAINT CHECK - NIVEL COLUNA

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(4),
        NOME VARCHAR2(30),
        SEXO CHAR(1) CHECK (SEXO IN('M', 'F', 'm', 'f'))
        );
        
--CRIACAO DA TABELA ALUNO COM CONSTRAIN CHECK NOMEADA - NIVEL COLUNA

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(4),
        NOME VARCHAR2(30),
        SEXO CHAR(1) CONSTRAINT CK_ALUNO_SEXO CHECK (SEXO IN('M', 'F'))
        );
    
--CRIACAO DA TABELA ALUNO COM CONSTRAINT CHECK NOMEADA - NIVEL TABELA

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(4),
        NOME VARCHAR2(30),
        SEXO CHAR(1),
        CONSTRAINT CK_ALUNO_SEXO CHECK (SEXO IN('M', 'F'))
        );
    
--EXCLUIR A TABELA ALUNO (NOVAMENTE)

DROP TABLE ALUNO CASCADE CONSTRAINTS;

--CRIACAO DE TABELA ALUNO SEM CONSTRAINT NOMEADA

CREATE TABLE
    ALUNO (
        MATRICULA NUMBER(4) PRIMARY KEY,
        NOME VARCHAR2(30),
        SEXO CHAR(1) CHECK (SEXO IN ('M', 'F'))
        );
        
-- CRIACAO DE TABELA CELULAR SEM CONSTRAINT NOMEADA - FOREING KEY

CREATE TABLE
    CELULAR (
        COD_CELULAR NUMBER(4) PRIMARY KEY,
        NUMERO VARCHAR2(11) UNIQUE,
        MATRICULA NUMBER(4) REFERENCES ALUNO (MATRICULA)
        );
        
-- EXCLUIR A TABELA CELULAR

DROP TABLE CELULAR CASCADE CONSTRAINTS;

-- CRIACAO DE TABELA CELULAR COM CONSTRAINT NOMEADA - FOREING KEY - NÍVEL COLUNA

CREATE TABLE
    CELULAR (
        COD_CELULAR NUMBER(4) CONSTRAINT PK_CELULAR_COD_CELULAR PRIMARY KEY,
        NUMERO VARCHAR(11) CONSTRAINT UK_CELULAR_NUMERO UNIQUE,
        MATRICULA NUMBER(4) CONSTRAINT FK_CELULAR_ALUNO_MATRICULA 
        REFERENCES ALUNO (MATRICULA)
        );
    
-- CRIACAO DE TABELA CELULAR COM CONSTRAINT NOMEADA - FOREING KEY - NÍVEL TABELA

CREATE TABLE
    CELULAR (
        COD_CELULAR NUMBER(4) CONSTRAINT PK_CELULAR_COD_CELULAR PRIMARY KEY,
        NUMERO VARCHAR2(11) CONSTRAINT UK_CELULAR_NUMERO UNIQUE,
        CPF VARCHAR2(14),
        MATRICULA NUMBER(4),
        CONSTRAINT FK_CELULAR_ALUNO_CPF_MATRICULA FOREIGN KEY(CPF, MATRICULA)
        REFERENCES ALUNO (CPF, MATRICULA)
        );
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        