-- AULA 02 - EXERCICIOS

-- EXCLUI AS TABELAS

DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE MATERIA_PRIMA CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;

-- CRIA TABELA CATEGORIA

CREATE TABLE
    CATEGORIA (
        COD_CATEGORIA INT CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY,
        CATEGORIA VARCHAR2(255) CONSTRAINT UK_CATEGORIA UNIQUE,
        CONSTRAINT CK_CATEGORIA CHECK 
        (CATEGORIA IN ('DOCE', 'BEBIDA', 'CONGELADO'))
        );
        
-- CRIA TABELA MATERIA_PRIMA 

CREATE TABLE
    MATERIA_PRIMA (
        COD_MATERIA_PRIMA INT CONSTRAINT PK_MATERIA_PRIMA PRIMARY KEY,
        MATERIA_PRIMA VARCHAR2(255) CONSTRAINT UK_MATERIA_PRIMA UNIQUE
        );
        
-- CRIA TABELA PRODUTO

CREATE TABLE
    PRODUTO (
        COD_PRODUTO INT CONSTRAINT PK_PRODUTO PRIMARY KEY,
        COD_CATEGORIA INT CONSTRAINT NN_PRODUTO_COD_CATEGORIA NOT NULL
        CONSTRAINT FK_PRODUTO_COD_CATEGORIA REFERENCES CATEGORIA,
        PRODUTO VARCHAR2(255) CONSTRAINT UK_PRODUTO UNIQUE
        );
        
-- CRIA TABELA ITEM_PRODUTO - COLUNA

CREATE TABLE
    ITEM_PRODUTO (
        COD_PRODUTO INT CONSTRAINT FK_ITEM_PRODUTO_PRODUTO REFERENCES PRODUTO,
        COD_MATERIA_PRIMA INT CONSTRAINT FK_ITEM_PRODUTO_MATERIA_PRIMA REFERENCES MATERIA_PRIMA,
        QUANTIDADE INT CONSTRAINT NN_ITEM_PRODUTO_QTD NOT NULL,
        CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA)
        );
        
-- CRIA TABELA ITEM_PRODUTO - TABELA

CREATE TABLE
    ITEM_PRODUTO ( 
        COD_PRODUTO INT,
        COD_MATERIA_PRIMA INT,
        QUANTIDADE INT CONSTRAINT NN_ITEM_PRODUTO_QTD NOT NULL,
        CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_MATERIA_PRIMA),
        CONSTRAINT FK_ITEM_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO,
        CONSTRAINT FK_ITEM_PRODUTO_MATERIA_PRIMA FOREIGN KEY (COD_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA
        );
    












